# Calcul de l'enveloppe convexe du système Fe-Cu-Co-Ni 
Données extraites de Materials Project

In [1]:
# Paquet necessaire : numpy, pandas, scipy, convexhull
import numpy as np
import sys
import pandas as pd
from convexhull import cvhull

In [3]:
df = pd.read_csv("data_test/data3.csv")
df

            id     formule  Fe  Cu  Co  Ni  somme     E
0   mp-1245108          Fe   1   0   0   0      1 -8.19
1   mp-1271198          Fe   1   0   0   0      1 -8.42
2        mp-13          Fe   1   0   0   0      1 -8.47
3   mp-1194030          Fe   1   0   0   0      1 -8.29
4   mp-1271068          Fe   1   0   0   0      1 -8.45
..         ...         ...  ..  ..  ..  ..    ...   ...
78  mp-1225698       Cu₃Ni   0   3   0   1      4 -4.47
79  mp-1225695        CuNi   0   1   0   1      2 -4.87
80  mp-1225687        CuNi   0   1   0   1      2 -4.92
81  mp-1184069        CuNi   0   1   0   1      2 -4.91
82  mp-1224973      FeCuNi   1   1   0   1      3 -6.05

[83 rows x 8 columns]

In [4]:
energie = df.loc[:,'E']
enerige = np.array(energie,'float64')

nom = [x.strip() for x in df.loc[:,'id']]
nom = list(nom)

element = ['Fe','Cu','Co','Ni']
c = len(element)
compo = df.loc[:,element]
compo = np.array(compo,'float64')

energie.shape, len(nom), compo.shape

((83,), 83, (83, 4))

In [5]:
# Si besoin, on transforme les nombres d'élément en compostion
compo = [[y/x.sum() for y in x] for x in compo]
compo = np.array(compo,'float64')
compo

array([[1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [0.625     , 0.        , 0.375     , 0.        ],
       [0.8125    , 0.        , 0.1875    , 0.        ],
       [0.5625    , 0.        , 0.4375    , 0.        ],
       [0.875     , 0.        , 0.125     , 0.        ],
       [0.9375    , 0.        , 0.0625    , 0.        ],
       [0.25      , 0.        , 0.75      , 0.        ],
       [0.25      , 0.        , 0.75      , 0.        ],
       [0.75      , 0.        , 0.25      , 0.        ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.6875    , 0.        , 0.3125    , 0.        ],
       [0.1       , 0.        , 0.9       , 0.        ],
       [0.33333333, 0.        , 0.        , 0.66666667],
       [0.6       , 0.        , 0.        , 0.4       ],
       [0.75      , 0.        , 0.        , 0.25      ],
       [0.75      , 0.        , 0.        , 0.25      ],
       [0.75      , 0.        , 0.        , 0.25      ],
       [0.75      , 0.        , 0.        , 0.25      ],
       [0.75      , 0.        , 0.        , 0.25      ],
       [0.66666667, 0.        , 0.        , 0.33333333],
       [0.66666667, 0.        , 0.        , 0.33333333],
       [0.25      , 0.        , 0.        , 0.75      ],
       [0.25      , 0.        , 0.        , 0.75      ],
       [0.25      , 0.        , 0.        , 0.75      ],
       [0.25      , 0.        , 0.        , 0.75      ],
       [0.25      , 0.        , 0.        , 0.75      ],
       [0.5       , 0.        , 0.        , 0.5       ],
       [0.5       , 0.        , 0.        , 0.5       ],
       [0.5       , 0.        , 0.        , 0.5       ],
       [0.75      , 0.25      , 0.        , 0.        ],
       [0.75      , 0.25      , 0.        , 0.        ],
       [0.75      , 0.25      , 0.        , 0.        ],
       [0.2       , 0.8       , 0.        , 0.        ],
       [0.25      , 0.75      , 0.        , 0.        ],
       [0.25      , 0.75      , 0.        , 0.        ],
       [0.5       , 0.5       , 0.        , 0.        ],
       [0.        , 0.        , 0.75      , 0.25      ],
       [0.        , 0.        , 0.75      , 0.25      ],
       [0.        , 0.        , 0.75      , 0.25      ],
       [0.        , 0.        , 0.5       , 0.5       ],
       [0.        , 0.        , 0.5       , 0.5       ],
       [0.        , 0.        , 0.5       , 0.5       ],
       [0.        , 0.        , 0.25      , 0.75      ],
       [0.        , 0.        , 0.25      , 0.75      ],
       [0.        , 0.25      , 0.75      , 0.        ],
       [0.        , 0.25      , 0.        , 0.75      ],
       [0.        , 0.25      , 0.        , 0.75      ],
       [0.        , 0.75      , 0.        , 0.25      ],
       [0.        , 0.5       , 0.        , 0.5       ],
       [0.        , 0.5       , 0.        , 0.5       ],
       [0.        , 0.5       , 0.        , 0.5       ],
       [0.33333333, 0.33333333, 0.        , 0.33333333]])

In [7]:
hull = cvhull(nom, compo, energie)
hull

In [9]:
hull.stable

array([ 2, 13, 21, 29, 35, 38, 40, 55, 58, 68], dtype=int32)

In [10]:
hull.nom

['mp-1245108',
 'mp-1271198',
 'mp-13',
 'mp-1194030',
 'mp-1271068',
 'mp-1271128',
 'mp-1096950',
 'mp-136',
 'mp-568345',
 'mp-150',
 'mp-1193227',
 'mp-1271142',
 'mp-669382',
 'mp-54',
 'mp-1183710',
 'mp-102',
 'mp-1072089',
 'mp-1014111',
 'mp-1094136',
 'mp-1246134',
 'mp-10257',
 'mp-23',
 'mp-1008728',
 'mp-1056079',
 'mp-1059259',
 'mp-1010136',
 'mp-1120774',
 'mp-989695',
 'mp-989782',
 'mp-30',
 'mp-998890',
 'mp-1084832',
 'mp-641526',
 'mp-601842',
 'mp-1080603',
 'mp-18695',
 'mp-1225083',
 'mp-1007852',
 'mp-601820',
 'mp-1225016',
 'mp-2090',
 'mp-601848',
 'mp-1096987',
 'mp-1072076',
 'mp-1225009',
 'mp-1224780',
 'mp-1007862',
 'mp-1224827',
 'mp-999189',
 'mp-1007853',
 'mp-1224697',
 'mp-1077745',
 'mp-1079337',
 'mp-1007855',
 'mp-1225078',
 'mp-1418',
 'mp-1007854',
 'mp-1224965',
 'mp-2213',
 'mp-1224976',
 'mp-1225131',
 'mp-1184311',
 'mp-1184260',
 'mp-1224977',
 'mp-1224953',
 'mp-1184444',
 'mp-1224945',
 'mp-1226559',
 'mp-1183837',
 'mp-1008349',
 'mp-1226063',
 'mp-1226076',
 'mp-1006883',
 'mp-1183785',
 'mp-1183751',
 'mp-1183752',
 'mp-1225694',
 'mp-1184054',
 'mp-1225698',
 'mp-1225695',
 'mp-1225687',
 'mp-1184069',
 'mp-1224973']

## Listes des pahses stables

In [8]:
print('La base contient {} composés dont {} stables'.format(hull.npoints,len(hull.stable)))
print()
print('Listes des phases stables:')
print('--------------------------')
print()

fmt = '{:2} | {:10} | '+c*'{:6.4f} '+'| {:12.4f}'
fmt_title = '{:>2} | {:^10} | '+c*'x({:2})  '+'| {:^12}'
separation = 3*'-'+'|'+12*'-'+'|'+29*'-'+'|'+14*'-'

print(fmt_title.format('i', 'Nom (MP)',*element, 'E_DFT'))
print(separation)
for i in hull.stable :
    print(fmt.format(i, hull.nom[i], *hull.composition[i], hull.energie[i]))

La base contient 83 composés dont 10 stables

Listes des phases stables:
--------------------------

 i |  Nom (MP)  | x(Fe)  x(Cu)  x(Co)  x(Ni)  |    E_DFT
---|------------|-----------------------------|--------------
 2 | mp-13      | 1.0000 0.0000 0.0000 0.0000 |      -8.4700
13 | mp-54      | 0.0000 0.0000 1.0000 0.0000 |      -7.1100
21 | mp-23      | 0.0000 0.0000 0.0000 1.0000 |      -5.7800
29 | mp-30      | 0.0000 1.0000 0.0000 0.0000 |      -4.1000
35 | mp-18695   | 0.9375 0.0000 0.0625 0.0000 |      -8.4000
38 | mp-601820  | 0.7500 0.0000 0.2500 0.0000 |      -8.1800
40 | mp-2090    | 0.5000 0.0000 0.5000 0.0000 |      -7.8600
55 | mp-1418    | 0.2500 0.0000 0.0000 0.7500 |      -6.5400
58 | mp-2213    | 0.5000 0.0000 0.0000 0.5000 |      -7.1900
68 | mp-1183837 | 0.0000 0.0000 0.7500 0.2500 |      -6.8000

## Information pour un composé donné

In [11]:
compose='mp-2090'
#
print('Info sur le composé :',compose)
print('------------------------------------')
print('E=',hull.energie_compose(compose))
hull.distance_hull(compose)
pass

Info sur le composé : mp-2090
------------------------------------
E= -7.86
Le composé mp-2090  est stable

In [8]:
compose='mp-1006883'
#
print('Info sur le composé :',compose)
print('------------------------------------')
print('E=',hull.energie_compose(compose))
hull.distance_hull(compose)
pass

Info sur le composé : mp-1006883
------------------------------------
E= -6.29
Le composé mp-1006883  n'est pas stable
--------------------------------------------
ΔH = 0.1700
Il se décompose en :
0.6667(mp-1183837) + 0.3333(mp-23)

## Information pour une composition donnée

In [9]:
composition=[0.2,0.5,0.2,0.1]
#
txt='Compsiton :'
for j in range(hull.dim):
    txt+=' {:5.2f}'.format(composition[j])
print(txt)
print("----------------------------------------")
hull.phases_stables([0.2,0.5,0.2,0.1])
print("----------------------------------------")
print("L'enrgie de cette phase ou de ce mélange de phase est : {:8.4f}".format(hull.energie_hull(composition)[0]))

Compsiton :  0.20  0.50  0.20  0.10
----------------------------------------
Les phases stables sont :
0.3400(mp-2090) + 0.0400(mp-1183837) + 0.1200(mp-1418) + 0.5000(mp-30)
----------------------------------------
L'enrgie de cette phase ou de ce mélange de phase est :  -5.7792

## Ecart à l'enveloppe pour tous les composés

In [11]:
keys, data = hull.tableau_complet(element)
# keys, data = hull.tableau_complet(element, save_csv=True) # Enregistre le tableau dans un format csv
df = pd.DataFrame(data, columns=keys)
df

,Nom,x(Fe),x(Cu),x(Co),x(Ni),Stabilité,Ecart à l'enveloppe
0,mp-1245108,1.000000,0.000000,0.0,0.000000,non,0.28
1,mp-1271198,1.000000,0.000000,0.0,0.000000,non,0.05
2,mp-13,1.000000,0.000000,0.0,0.000000,oui,0.00
3,mp-1194030,1.000000,0.000000,0.0,0.000000,non,0.18
4,mp-1271068,1.000000,0.000000,0.0,0.000000,non,0.02
...,...,...,...,...,...,...,...
78,mp-1225698,0.000000,0.750000,0.0,0.250000,non,0.05
79,mp-1225695,0.000000,0.500000,0.0,0.500000,non,0.07
80,mp-1225687,0.000000,0.500000,0.0,0.500000,non,0.02
81,mp-1184069,0.000000,0.500000,0.0,0.500000,non,0.03
82,mp-1224973,0.333333,0.333333,0.0,0.333333,non,0.11